Statistics Infrastructure github clones
citusdata/tools pull request #122
Opened 2021-06-29 05:32 UTC by gurkanindibay

2021-06-29 19:27 UTC, halilozanakgul requested changes
I think we haven't been tracking `uniques` but I think it is good that we add it.

2021-06-29 19:27 UTC, halilozanakgul commented on packaging_automation/github_stats_collector.py
> +                                                        repo_name=repo_name, uniques=contents['uniques'])
I'm a bit confused here. Doesn't `get_clones_traffic` in `github_clone_stats` return a list of clone objects. Why would the contents include `count` and `unique`? Am I reading the docs wrong?

2021-06-29 19:27 UTC, halilozanakgul commented on packaging_automation/github_stats_collector.py
> +        detail_transaction = GithubCloneStatsTransactionsDetail(clone_date=daily_record.timestamp,
What is the purpose of the `GithubCloneStatsTransactionsDetail`? It feels like it is `GithubCloneStats` with less info.

2021-06-29 19:27 UTC, halilozanakgul commented on packaging_automation/tests/test_github_stats_collector.py
> +    assert not today_record.first()
Maybe we could also look at the `GithubCloneStatsTransactionsMain` table too.

2021-07-01 15:20 UTC, halilozanakgul approved these changes

2021-07-02 05:25 UTC, gurkanindibay commented on packaging_automation/bash/daily-statistics-job.sh
> +  python -m packaging_automation.github_stats_collector --repo_name citus \
Fixed

2021-07-02 05:28 UTC, gurkanindibay commented on packaging_automation/github_statistics_collector.py
> +        # stat record will not be added if it exists in
Fixed

2021-07-02 05:34 UTC, merged