Adds packaging images release name support into citus package
citusdata/tools pull request #177
Opened 2021-09-06 07:31 UTC by gurkanindibay

Packaging images creation release names are different than standard release names. Packaging images release names are seperated by comma but our general release names are seperated by '/'. Some release names are totally different as well like redhat and oracle. 
In this PR, I added a map to support the ones seperated with comma

2021-09-28 12:05 UTC, hanefi reviewed
What do you think about using only `/` characters and stop using `,` to separate OS name and release identifiers? Do you think it would be easier to handle?

2021-09-28 12:45 UTC, hanefi requested changes

2021-09-28 12:45 UTC, hanefi commented on packaging_automation/tests/test_citus_package.py
> +#         run("rm -r packaging_test")
I do not like these commented out lines

2021-09-28 12:45 UTC, hanefi commented on packaging_automation/citus_package.py
> +        os_name = os_name if os_name != "centos" else "el"
```suggestion
        os_name = "ol" if os_name == "oraclelinux" else os_name
        os_name = "el" if os_name == "centos" else os_name
```

I think this one is easier to read and understand.

2021-09-29 06:50 UTC, gurkanindibay commented
> What do you think about using only `/` characters and stop using `,` to separate OS name and release identifiers? Do you think it would be easier to handle?

there are lots of place to change and it is risky and will take too much time. I need to finish conversion ASAP

2021-09-29 07:03 UTC, gurkanindibay commented on packaging_automation/tests/test_citus_package.py
> +#         run("rm -r packaging_test")
My misatake. Uncommented lines

2021-09-30 08:10 UTC, hanefi approved these changes
I am not totally comfortable with adding yet another argument to this cli tool. The arguments are not documented well and it is not so easy to understand their purposes without digging deeper into the codebase. I have a hard time creating packages on my local machine now, and it appears that it will be even harder than before.

I hope that we can make these tools more user friendly in the future.

2021-09-30 08:29 UTC, merged